lib/sceopa/web/router.ex
defmodule Sceopa.Web.Router do
  use Sceopa.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Sceopa.Web.Plugs.Auth, repo: Sceopa.Repo
  end

  scope "/", Sceopa.Web do
    pipe_through :browser

    get "/", PageController, :index

    get "/about", AboutController, :index

    get "/users/sign_in", SessionController, :new
    post "/users/sign_in", SessionController, :create
    get "/users/sign_out", SessionController, :delete

    resources "/users", UserController, only: [:new, :create, :delete, :show] do
      get "/posts/export", ExportPostsController, :index
      get "/posts/import", ImportPostsController, :index
      post "/posts/import", ImportPostsController, :update
    end

    get "/user/settings", UserSettingsController, :index
    get "/user/password", UserSettingsPasswordController, :edit
    put "/user/password", UserSettingsPasswordController, :update
    get "/user/username", UserSettingsUsernameController, :edit
    put "/user/username", UserSettingsUsernameController, :update

    get "/email/verify", EmailController, :index

    get "/dashboard", DashboardController, :index

    resources "/posts", PostController, except: [:index]
  end
end

lib/sceopa/web/controllers/import_posts_controller.ex
defmodule Sceopa.Web.ImportPostsController do
  @moduledoc """
  Provides action for uploading posts.
  """

  use Sceopa.Web, :controller
  import Sceopa.Web.Plugs.Auth
  import Sceopa.Web.Plugs.User

  alias Sceopa.Blog

  plug :authenticate
  plug :ensure_user

  def index(conn, _params) do
    user = conn.assigns.current_user
    render(conn, "index.html", user: user)
  end

  def update(conn, %{"file" => file}) do
    user = conn.assigns.current_user

    case Blog.import_posts(user, file) do
      {:ok} ->
        conn
        |> put_flash(:info, "Posts successfully imported!")
        |> redirect(to: dashboard_path(conn, :index))
      _ ->
        conn
        |> put_flash(:error, "There was an error importing your posts,\
        please check your JSON and try again.")
        |> render("index.html", user: user)
    end
  end
end

lib/sceopa/web/views/import_posts_view.ex
defmodule Sceopa.Web.ImportPostsView do
  use Sceopa.Web, :view
end

lib/sceopa/web/templates/import_posts/index.html.eex
<h1>Upload posts</h1>

<p>You can upload multiple posts at once using a JSON file with the following format:</p>

<pre>
{
    "posts": [{
        "title": "An example article",
        "public": false,
        "inserted_at": "2017-02-20T17:10:02.165835",
        "updated_at": "2017-02-20T17:10:02.173398",
        "content": "Lorem ipsum dolor sit amet..."
    }]
}
</pre>

<p>where the <em>inserted_at</em> and <em>updated_at</em> fields are in ISO 8601 format.</p>

<%= form_for @conn, user_import_posts_path(@conn, :update, @user.id), [as: :import_posts, multipart: true], fn _f -> %>
  <div class="form-group">
    <input type="file" id="file" name="file" accept=".json" required />
  </div>

  <%= submit "Upload posts", class: "button-small" %>
<% end %>