lib/sceopa/web/router.ex
defmodule Sceopa.Web.Router do
  use Sceopa.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Sceopa.Web.Plugs.Auth, repo: Sceopa.Repo
  end

  scope "/", Sceopa.Web do
    pipe_through :browser

    get "/", PageController, :index

    get "/about", AboutController, :index

    get "/users/sign_in", SessionController, :new
    post "/users/sign_in", SessionController, :create
    get "/users/sign_out", SessionController, :delete

    resources "/users", UserController, only: [:new, :create, :delete, :show] do
      get "/posts/export", ExportPostsController, :index
      get "/posts/import", ImportPostsController, :index
      post "/posts/import", ImportPostsController, :update
    end

    get "/user/settings", UserSettingsController, :index
    get "/user/password", UserSettingsPasswordController, :edit
    put "/user/password", UserSettingsPasswordController, :update
    get "/user/username", UserSettingsUsernameController, :edit
    put "/user/username", UserSettingsUsernameController, :update

    get "/email/verify", EmailController, :index

    get "/dashboard", DashboardController, :index

    resources "/posts", PostController, except: [:index]
  end
end

lib/sceopa/web/templates/page/index.html.eex
<h1>Blogging made simple</h1>
<br>
<a href="<%= user_path(@conn, :new) %>" class="button-large">Create an account</a>
<br>
<br>
<p><em>Sceopa</em> is a free, open-source blogging platform designed for simplicity and ease of use.</p>

<h2>Fast and responsive on all devices</h2>
<ul>
  <li>No javascript</li>
  <li>No custom fonts</li>
  <li>Minimal CSS</li>
</ul>

<h2>Optimized for reading</h2>
<ul>
  <li>Large, clear text</li>
  <li>Minimal design, no distractions</li>
</ul>

<h2>Designed for coders</h2>
<ul>
  <li>Inbuilt syntax highlighting</li>
  <li>Markdown support</li>
  <li>Open-source (GPL v3) on <a href="https://gitlab.com/jameslong/sceopa">GitLab</a></li>
</ul>

<a href="<%= about_path(@conn, :index) %>">Find out more.</a>