lib/sceopa/web/router.ex
defmodule Sceopa.Web.Router do
  use Sceopa.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Sceopa.Web.Plugs.Auth, repo: Sceopa.Repo
  end

  scope "/", Sceopa.Web do
    pipe_through :browser

    get "/", PageController, :index

    get "/about", AboutController, :index

    get "/users/sign_in", SessionController, :new
    post "/users/sign_in", SessionController, :create
    get "/users/sign_out", SessionController, :delete

    resources "/users", UserController, only: [:new, :create, :delete, :show] do
      get "/posts/export", ExportPostsController, :index
      get "/posts/import", ImportPostsController, :index
      post "/posts/import", ImportPostsController, :update
    end

    get "/user/settings", UserSettingsController, :index
    get "/user/password", UserSettingsPasswordController, :edit
    put "/user/password", UserSettingsPasswordController, :update
    get "/user/username", UserSettingsUsernameController, :edit
    put "/user/username", UserSettingsUsernameController, :update

    get "/email/verify", EmailController, :index

    get "/dashboard", DashboardController, :index

    resources "/posts", PostController, except: [:index]
  end
end

lib/sceopa/web/controllers/user_settings_controller.ex
defmodule Sceopa.Web.UserSettingsController do
  use Sceopa.Web, :controller

  import Sceopa.Web.Plugs.Auth
  plug :authenticate

  def index(conn, _params) do
    user = conn.assigns.current_user
    render(conn, "index.html", user: user)
  end
end

lib/sceopa/web/views/user_settings_view.ex
defmodule Sceopa.Web.UserSettingsView do
  use Sceopa.Web, :view
end

lib/sceopa/web/templates/user_settings/index.html.eex
<h1>Settings</h1>

<div><a href="<%= user_settings_username_path(@conn, :edit) %>">Change username</a></div>
<div><a href="<%= user_settings_password_path(@conn, :edit) %>">Change password</a></div>
<form action="<%= user_path(@conn, :delete, @user) %>" method="post" class="form-link">
  <input name="_method" type="hidden" value="delete">
  <input name="_csrf_token" type="hidden" value="<%= get_csrf_token() %>">
  <input type="submit" value="Delete account">
</form>