lib/sceopa/web/router.ex
defmodule Sceopa.Web.Router do
  use Sceopa.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Sceopa.Web.Plugs.Auth, repo: Sceopa.Repo
  end

  scope "/", Sceopa.Web do
    pipe_through :browser

    get "/", PageController, :index

    get "/about", AboutController, :index

    get "/users/sign_in", SessionController, :new
    post "/users/sign_in", SessionController, :create
    get "/users/sign_out", SessionController, :delete

    resources "/users", UserController, only: [:new, :create, :delete, :show] do
      get "/posts/export", ExportPostsController, :index
      get "/posts/import", ImportPostsController, :index
      post "/posts/import", ImportPostsController, :update
    end

    get "/user/settings", UserSettingsController, :index
    get "/user/password", UserSettingsPasswordController, :edit
    put "/user/password", UserSettingsPasswordController, :update
    get "/user/username", UserSettingsUsernameController, :edit
    put "/user/username", UserSettingsUsernameController, :update

    get "/email/verify", EmailController, :index

    get "/dashboard", DashboardController, :index

    resources "/posts", PostController, except: [:index]
  end
end

lib/sceopa/web/views/layout_view.ex
defmodule Sceopa.Web.LayoutView do
  use Sceopa.Web, :view
end

lib/sceopa/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Sceopa!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render Sceopa.Web.LayoutView, "header.html", conn: @conn, current_user: @current_user %>

    <main>
      <%= if get_flash(@conn, :error) do %>
        <div class="flash-error">
          <%= get_flash(@conn, :error) %>
        </div>
      <% end %>
      <%= if get_flash(@conn, :info) do %>
        <div class="flash-info">
          <%= get_flash(@conn, :info) %>
        </div>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </main>
  </body>
</html>

lib/sceopa/web/templates/layout/header.html.eex
<header>
  <span><a href="<%= page_path(@conn, :index) %>" class="logo">Sceopa</a></span>
  <nav>
    <ul>
      <%= if @current_user == nil do %>
        <li><a href="<%= user_path(@conn, :new) %>" class="button-small">Sign up</a></li>
        <li><a href="<%= session_path(@conn, :new) %>">Sign in</a></li>
      <%= else %>
        <li><a href="<%= post_path(@conn, :new) %>">+ Add post</a></li>
        <li><a href="<%= user_path(@conn, :show, @current_user) %>">Blog</a></li>
        <li><a href="<%= dashboard_path(@conn, :index) %>">Dashboard</a></li>
        <li><a href="<%= user_settings_path(@conn, :index) %>">Settings</a></li>
        <li><a href="<%= session_path(@conn, :delete) %>">Sign out</a></li>
      <% end %>
    </ul>
  </nav>
</header>